newIssueWelcomeComment: >
  Congrats on creating your first Issue in the C0DING Organization! 🎉

newPRWelcomeComment: >
  Congrats on making your first Pull Request in the C0DING Organization! 🥳

firstPRMergeComment: >
  Congrats on merging your first pull request! We are proud of you! 🤗
  We invited you to join our organization please check your email. 🚀
